In [2]:
#1D array join
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))#default axis=0
print(arr)

[1 2 3 4 5 6]


In [5]:
#2D array with axis=0
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#2D array with axis=1
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
