In [1]:
#Use of stack fun
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.stack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
#Use of hstack fun:-stack along row 
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
#Use of vstack fun:-stack along col
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#Use of dstack fun:-stack along height similar to depth
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
