In [1]:
#Cumulative sum:-sum of all previous element
import numpy as np
arr=np.array([1,2,3,4])
print(np.cumsum(arr))

[ 1  3  6 10]


In [3]:
#Cumsumm of 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.cumsum(arr))

[ 1  3  6 10 15 21]


In [2]:
#Cmulative product:-prod of all  previous element
import numpy as np
arr=np.array([1,2,3,4])
print(np.cumprod(arr))

[ 1  2  6 24]
