In [2]:
#0-D array/Scalars
import numpy as np
arr=np.array(42)
print(arr)
print(arr.ndim)

42
0


In [3]:
#1-D array/Vector
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [4]:
#2-D array/Matrix
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [5]:
#3-D array/Tensor
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]]
3
