In [5]:
#Add scalar to array
import numpy as np
arr=np.array([1, 2, 3, 4, 5])
result=arr+5
print(arr+5)
print(result)


[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [6]:
#Add 1D t0 2D
import numpy as np
a=np.array([[1,2,3],[4,5,6]])#3,2
b=np.array([10,20,30])#3
print(a+b)

[[11 22 33]
 [14 25 36]]


In [8]:
#Add 1d into 3D
import numpy as np
a=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])#2,2,1
b=np.array([1,2])#2
print(a+b)

[[[2 4]
  [3 5]]

 [[4 6]
  [5 7]]]


In [9]:
#Add 2d to 3D
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
b=np.array([[1,3],[2,5]])
print(a+b)

[[[ 2  5]
  [ 5  9]]

 [[ 6  9]
  [ 8 12]]]
